// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
export const edit = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(options),
    method: "get",
})

edit.definition = {
    methods: ["get","head"],
    url: "/settings/appearance",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
edit.url = (options?: RouteQueryOptions) => {
    return edit.definition.url + queryParams(options)
}

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
edit.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(options),
    method: "get",
})

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
edit.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: edit.url(options),
    method: "head",
})

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
const editForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(options),
    method: "get",
})

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
editForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(options),
    method: "get",
})

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/routes/settings.php:25
 * @route "/settings/appearance"
 */
editForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(formSafeOptions("head", options)),
    method: "get",
})

edit.form = editForm

const appearance = {
    edit,
}

export default appearance