// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Routing from "./Routing";

export const Illuminate = {
    Routing,
}

export default Illuminate