// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Fortify from "./Fortify";
import Telescope from "./Telescope";

export const Laravel = {
    Fortify,
    Telescope,
}

export default Laravel