// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:53
 * @route "/register"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/register",
} satisfies RouteDefinition<["post"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:53
 * @route "/register"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:53
 * @route "/register"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:53
 * @route "/register"
 */
const storeForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RegisteredUserController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RegisteredUserController.php:53
 * @route "/register"
 */
storeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

store.form = storeForm

const register = {
    store,
}

export default register