// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
export const show = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/blog/{post}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
show.url = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { post: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "slug" in args) {
        args = { post: args.slug }
    }
    
    if (Array.isArray(args)) {
        args = {
        post: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        post: typeof args.post === "object" ? args.post.slug : args.post,
    }
    
    return show.definition.url
        .replace("{post}", parsedArgs.post.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
show.get = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
show.head = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
const showForm = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
showForm.get = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\PostController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/PostController.php:15
 * @route "/blog/{post}"
 */
showForm.head = (args: { post: string | { slug: string } } | [ post: string | { slug: string } ] | string | { slug: string }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, formSafeOptions("head", options)),
    method: "get",
})

show.form = showForm

const blog = {
    show,
}

export default blog