// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import PasswordController from "./PasswordController";
import ProfileController from "./ProfileController";
import TwoFactorAuthenticationController from "./TwoFactorAuthenticationController";

export const Settings = {
    PasswordController,
    ProfileController,
    TwoFactorAuthenticationController,
}

export default Settings