// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
export const edit = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(options),
    method: "get",
})

edit.definition = {
    methods: ["get","head"],
    url: "/settings/password",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
edit.url = (options?: RouteQueryOptions) => {
    return edit.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
edit.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
edit.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: edit.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
const editForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
editForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Settings\PasswordController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:16
 * @route "/settings/password"
 */
editForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(formSafeOptions("head", options)),
    method: "get",
})

edit.form = editForm
/**
 * @see \App\Http\Controllers\Settings\PasswordController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:24
 * @route "/settings/password"
 */
export const update = (options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(options),
    method: "put",
})

update.definition = {
    methods: ["put"],
    url: "/settings/password",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\Settings\PasswordController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:24
 * @route "/settings/password"
 */
update.url = (options?: RouteQueryOptions) => {
    return update.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Settings\PasswordController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:24
 * @route "/settings/password"
 */
update.put = (options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\Settings\PasswordController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:24
 * @route "/settings/password"
 */
const updateForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\Settings\PasswordController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/PasswordController.php:24
 * @route "/settings/password"
 */
updateForm.put = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(formSafeOptions("put", options)),
    method: "post",
})

update.form = updateForm

const PasswordController = {
    edit,
    update,
}

export default PasswordController