// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
export const show = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/settings/two-factor",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
show.url = (options?: RouteQueryOptions) => {
    return show.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
show.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
show.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
const showForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
showForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\Settings\TwoFactorAuthenticationController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/Settings/TwoFactorAuthenticationController.php:28
 * @route "/settings/two-factor"
 */
showForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(formSafeOptions("head", options)),
    method: "get",
})

show.form = showForm

const TwoFactorAuthenticationController = {
    show,
}

export default TwoFactorAuthenticationController