// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const DomainRegistriert = "domain_registriert"
export const ShopSystemEingerichtet = "shop_system_eingerichtet"
export const ZahlungsanbieterAngebunden = "zahlungsanbieter_angebunden"
export const RechtstexteIntegriert = "rechtstexte_integriert"
export const TrackingEingerichtet = "tracking_eingerichtet"
export const SeoGrundoptimierung = "seo_grundoptimierung"
export const ProduktdatenGepflegt = "produktdaten_gepflegt"
export const VersandstrukturDefiniert = "versandstruktur_definiert"
export const KundenserviceProzessDefiniert = "kundenservice_prozess_definiert"
export const NochNichtsVorhanden = "noch_nichts_vorhanden"

/**
 * @see [App\Enums\AcquiringCustomerOnlineShopEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/AcquiringCustomerOnlineShopEnum.php)
 */
export const AcquiringCustomerOnlineShopEnum = { DomainRegistriert, ShopSystemEingerichtet, ZahlungsanbieterAngebunden, RechtstexteIntegriert, TrackingEingerichtet, SeoGrundoptimierung, ProduktdatenGepflegt, VersandstrukturDefiniert, KundenserviceProzessDefiniert, NochNichtsVorhanden } as const

export default AcquiringCustomerOnlineShopEnum