// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const SelbstBaukasten = "selbst_baukasten"
export const Freelancer = "freelancer"
export const Agentur = "agentur"

/**
 * @see [App\Enums\AcquiringCustomerCreateOnlineShopEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/AcquiringCustomerCreateOnlineShopEnum.php)
 */
export const AcquiringCustomerCreateOnlineShopEnum = { SelbstBaukasten, Freelancer, Agentur } as const

export default AcquiringCustomerCreateOnlineShopEnum