// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const OnlineShop = "online_shop"
export const Direktvertrieb = "direktvertrieb"
export const Aussendienst = "aussendienst"
export const PartnerReseller = "partner_reseller"
export const Plattformen = "plattformen"
export const SocialMediaDirektverkauf = "social_media_direktverkauf"
export const Beratungsgespraeche = "beratungsgespraeche"
export const StationaeresGeschaeft = "stationaeres_geschaeft"

/**
 * @see [App\Enums\AcquiringCustomersEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/AcquiringCustomersEnum.php)
 */
export const AcquiringCustomersEnum = { OnlineShop, Direktvertrieb, Aussendienst, PartnerReseller, Plattformen, SocialMediaDirektverkauf, Beratungsgespraeche, StationaeresGeschaeft } as const

export default AcquiringCustomersEnum