// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Unter25 = "unter_25"
export const Jahre25bis35 = "25_35"
export const Jahre36bis50 = "36_50"
export const Ab50 = "50_plus"

/**
 * @see [App\Enums\AgeGroupEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/AgeGroupEnum.php)
 */
export const AgeGroupEnum = { Unter25, Jahre25bis35, Jahre36bis50, Ab50 } as const

export default AgeGroupEnum