// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const ProductSales = "product_sales"
export const Services = "services"
export const Marketplace = "marketplace"
export const AboModel = "abo_model"
export const LicenseModel = "license_model"
export const Franchise = "franchise"

/**
 * @see [App\Enums\BusinessModelEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/BusinessModelEnum.php)
 */
export const BusinessModelEnum = { ProductSales, Services, Marketplace, AboModel, LicenseModel, Franchise } as const

export default BusinessModelEnum