// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Financial = "financial"
export const Investorengewinnung = "investorengewinnung"
export const Credit = "credit"
export const InternStrategy = "intern_strategy"
export const Funding = "funding"

/**
 * @see [App\Enums\BusinessplanTargetEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/BusinessplanTargetEnum.php)
 */
export const BusinessplanTargetEnum = { Financial, Investorengewinnung, Credit, InternStrategy, Funding } as const

export default BusinessplanTargetEnum