// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const NoRevenue = "no_revenue"
export const FirstSales = "first_sales"
export const PilotCustomer = "pilot_customer"

/**
 * @see [App\Enums\BusinessActivitiesEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/BusinessActivitiesEnum.php)
 */
export const BusinessActivitiesEnum = { NoRevenue, FirstSales, PilotCustomer } as const

export default BusinessActivitiesEnum