// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const ProductDevelopment = "product_development"
export const Employees = "employees"
export const Marketing = "marketing"
export const OperatingResources = "operating_resources"
export const Growth = "growth"
export const Reorientation = "reorientation"
export const EfficiencyImprovement = "efficiency_improvement"
export const Internationalization = "internationalization"

/**
 * @see [App\Enums\CapitalUsageEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/CapitalUsageEnum.php)
 */
export const CapitalUsageEnum = { ProductDevelopment, Employees, Marketing, OperatingResources, Growth, Reorientation, EfficiencyImprovement, Internationalization } as const

export default CapitalUsageEnum