// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const PRODUCT = "product"
export const SERVICE = "service"

/**
 * @see [App\Enums\CatalogTypeEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/CatalogTypeEnum.php)
 */
export const CatalogTypeEnum = { PRODUCT, SERVICE } as const

export default CatalogTypeEnum