// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const EigenerOnlineShop = "eigener_online_shop"
export const SocialMedia = "social_media"
export const EigeneApp = "eigene_app"
export const Direktvertrieb = "direktvertrieb"
export const PopUpStores = "popup_stores"

/**
 * @see [App\Enums\ChannelsEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/ChannelsEnum.php)
 */
export const ChannelsEnum = { EigenerOnlineShop, SocialMedia, EigeneApp, Direktvertrieb, PopUpStores } as const

export default ChannelsEnum