// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const B2B = "b2b"
export const B2C = "b2c"
export const D2C = "d2c"
export const B2G = "b2g"

/**
 * @see [App\Enums\ClientTypeEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/ClientTypeEnum.php)
 */
export const ClientTypeEnum = { B2B, B2C, D2C, B2G } as const

export default ClientTypeEnum