// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const UnderThousand = "under_thousand"
export const ThousandToTenThousand = "thousand_to_ten_thousand"
export const TenToHundredThousand = "ten_to_hundred_thousand"
export const OverHundredThousand = "over_hundred_thousand"

/**
 * @see [App\Enums\CommunityLeadershipEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/CommunityLeadershipEnum.php)
 */
export const CommunityLeadershipEnum = { UnderThousand, ThousandToTenThousand, TenToHundredThousand, OverHundredThousand } as const

export default CommunityLeadershipEnum