// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Startups = "startups"
export const Kmu = "kmu"
export const Mittelstand = "mittelstand"
export const Konzerne = "konzerne"

/**
 * @see [App\Enums\CompanyTargetGroupEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/CompanyTargetGroupEnum.php)
 */
export const CompanyTargetGroupEnum = { Startups, Kmu, Mittelstand, Konzerne } as const

export default CompanyTargetGroupEnum