// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const New = "new"
export const Existing = "existing"
export const Succession = "succession"

/**
 * @see [App\Enums\CompanyStateEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/CompanyStateEnum.php)
 */
export const CompanyStateEnum = { New, Existing, Succession } as const

export default CompanyStateEnum