// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Idee = "idee"
export const Prototyp = "prototyp"
export const Mvp = "mvp"
export const Marktreif = "marktreif"
export const BereitsAmMarkt = "bereits_am_markt"

/**
 * @see [App\Enums\DevelopmentStateEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/DevelopmentStateEnum.php)
 */
export const DevelopmentStateEnum = { Idee, Prototyp, Mvp, Marktreif, BereitsAmMarkt } as const

export default DevelopmentStateEnum