// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Gruender = "gruender"
export const Mitarbeiter = "mitarbeiter"
export const ExterneVertriebsagentur = "externe_vertriebsagentur"

/**
 * @see [App\Enums\DirectSalesResponsibilityEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/DirectSalesResponsibilityEnum.php)
 */
export const DirectSalesResponsibilityEnum = { Gruender, Mitarbeiter, ExterneVertriebsagentur } as const

export default DirectSalesResponsibilityEnum