// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Supplier = "supplier"
export const RawMaterials = "raw_materials"
export const Community = "community"
export const Relationships = "relationships"
export const Platforms = "platforms"

/**
 * @see [App\Enums\ExclusiveLeadershipEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/ExclusiveLeadershipEnum.php)
 */
export const ExclusiveLeadershipEnum = { Supplier, RawMaterials, Community, Relationships, Platforms } as const

export default ExclusiveLeadershipEnum