// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const VertriebsleitfadenVorhanden = "vertriebsleitfaden_vorhanden"
export const KundendatenbankVorhanden = "kundendatenbank_vorhanden"
export const CrmSystemEingerichtet = "crm_system_eingerichtet"
export const AngebotsvorlagenVorhanden = "angebotsvorlagen_vorhanden"
export const VerguetungsmodellDefiniert = "verguetungsmodell_definiert"
export const GeschultesPersonalVerfuegbar = "geschultes_personal_verfuegbar"
export const NochKeineStruktur = "noch_keine_struktur"

/**
 * @see [App\Enums\ExistingSalesStructureEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/ExistingSalesStructureEnum.php)
 */
export const ExistingSalesStructureEnum = { VertriebsleitfadenVorhanden, KundendatenbankVorhanden, CrmSystemEingerichtet, AngebotsvorlagenVorhanden, VerguetungsmodellDefiniert, GeschultesPersonalVerfuegbar, NochKeineStruktur } as const

export default ExistingSalesStructureEnum