// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const AussendienstmitarbeiterEingestellt = "aussendienstmitarbeiter_eingestellt"
export const FahrzeugeVorhanden = "fahrzeuge_vorhanden"
export const ReisekostenbudgetGeplant = "reisekostenbudget_geplant"
export const CrmSystemMobilNutzbar = "crm_system_mobil_nutzbar"
export const VertragsunterlagenVorbereitet = "vertragsunterlagen_vorbereitet"
export const VertriebszieleDefiniert = "vertriebsziele_definiert"
export const NochNichtsVorhanden = "noch_nichts_vorhanden"

/**
 * @see [App\Enums\FieldServiceInfrastructureEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/FieldServiceInfrastructureEnum.php)
 */
export const FieldServiceInfrastructureEnum = { AussendienstmitarbeiterEingestellt, FahrzeugeVorhanden, ReisekostenbudgetGeplant, CrmSystemMobilNutzbar, VertragsunterlagenVorbereitet, VertriebszieleDefiniert, NochNichtsVorhanden } as const

export default FieldServiceInfrastructureEnum