// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const NEW = "new"
export const EXPANSION = "expansion"
export const RESTRUCTURING = "restructuring"
export const RELOCATION = "relocation"
export const TAKEOVER = "takeover"

/**
 * @see [App\Enums\FoundationTypeEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/FoundationTypeEnum.php)
 */
export const FoundationTypeEnum = { NEW, EXPANSION, RESTRUCTURING, RELOCATION, TAKEOVER } as const

export default FoundationTypeEnum