// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const PENDING = "pending"
export const GENERATING = "generating"
export const COMPLETED = "completed"
export const FAILED = "failed"
export const CANCELLED = "cancelled"

/**
 * @see [App\Enums\GenerationStatusEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/GenerationStatusEnum.php)
 */
export const GenerationStatusEnum = { PENDING, GENERATING, COMPLETED, FAILED, CANCELLED } as const

export default GenerationStatusEnum