// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import AcquiringCustomerCreateOnlineShopEnum from "./AcquiringCustomerCreateOnlineShopEnum";
import InformationTargetGroupEnum from "./InformationTargetGroupEnum";
import ExclusiveLeadershipEnum from "./ExclusiveLeadershipEnum";
import TechnologyLeadershipEnum from "./TechnologyLeadershipEnum";
import SpecialistLeadershipEnum from "./SpecialistLeadershipEnum";
import ClientTypeEnum from "./ClientTypeEnum";
import FieldServiceInfrastructureEnum from "./FieldServiceInfrastructureEnum";
import BusinessActivitiesEnum from "./BusinessActivitiesEnum";
import CompanyTargetGroupEnum from "./CompanyTargetGroupEnum";
import TargetMarketEnum from "./TargetMarketEnum";
import ShippingOrganizationEnum from "./ShippingOrganizationEnum";
import ChannelsEnum from "./ChannelsEnum";
import PlanCrmIntroductionEnum from "./PlanCrmIntroductionEnum";
import GenerationStatusEnum from "./GenerationStatusEnum";
import PublicTenderEnum from "./PublicTenderEnum";
import BusinessplanTargetEnum from "./BusinessplanTargetEnum";
import CompanyStateEnum from "./CompanyStateEnum";
import MarketingInfrastructureEnum from "./MarketingInfrastructureEnum";
import StatusEnum from "./StatusEnum";
import CommunityLeadershipEnum from "./CommunityLeadershipEnum";
import CapitalUsageEnum from "./CapitalUsageEnum";
import SocialAdsPlatformsEnum from "./SocialAdsPlatformsEnum";
import InovationLevelEnum from "./InovationLevelEnum";
import LifeSituationEnum from "./LifeSituationEnum";
import ScalableCapabilityEnum from "./ScalableCapabilityEnum";
import MarketingResponsibilityEnum from "./MarketingResponsibilityEnum";
import PostCategoryEnum from "./PostCategoryEnum";
import AgeGroupEnum from "./AgeGroupEnum";
import TypeEnum from "./TypeEnum";
import MarketingExperienceEnum from "./MarketingExperienceEnum";
import AcquiringCustomersEnum from "./AcquiringCustomersEnum";
import PaymentMethodsEnum from "./PaymentMethodsEnum";
import PriceLeadershipEnum from "./PriceLeadershipEnum";
import QualityLeadershipEnum from "./QualityLeadershipEnum";
import BusinessModelEnum from "./BusinessModelEnum";
import PropertyRightsEnum from "./PropertyRightsEnum";
import OfferTypeEnum from "./OfferTypeEnum";
import MarketingChannelsEnum from "./MarketingChannelsEnum";
import DirectSalesResponsibilityEnum from "./DirectSalesResponsibilityEnum";
import MarketingBudgetEnum from "./MarketingBudgetEnum";
import PurchaseDecisionEnum from "./PurchaseDecisionEnum";
import PlanRecipientEnum from "./PlanRecipientEnum";
import PriceStrategieEnum from "./PriceStrategieEnum";
import PriceCalculationEnum from "./PriceCalculationEnum";
import DevelopmentStateEnum from "./DevelopmentStateEnum";
import UspEnum from "./UspEnum";
import SalesCompensationModelEnum from "./SalesCompensationModelEnum";
import ExistingSalesStructureEnum from "./ExistingSalesStructureEnum";
import FoundationTypeEnum from "./FoundationTypeEnum";
import LiquiditySectionEnum from "./LiquiditySectionEnum";
import PricingStrategieEnum from "./PricingStrategieEnum";
import CatalogTypeEnum from "./CatalogTypeEnum";
import AcquiringCustomerOnlineShopEnum from "./AcquiringCustomerOnlineShopEnum";

export const Enums = {
    AcquiringCustomerCreateOnlineShopEnum,
    InformationTargetGroupEnum,
    ExclusiveLeadershipEnum,
    TechnologyLeadershipEnum,
    SpecialistLeadershipEnum,
    ClientTypeEnum,
    FieldServiceInfrastructureEnum,
    BusinessActivitiesEnum,
    CompanyTargetGroupEnum,
    TargetMarketEnum,
    ShippingOrganizationEnum,
    ChannelsEnum,
    PlanCrmIntroductionEnum,
    GenerationStatusEnum,
    PublicTenderEnum,
    BusinessplanTargetEnum,
    CompanyStateEnum,
    MarketingInfrastructureEnum,
    StatusEnum,
    CommunityLeadershipEnum,
    CapitalUsageEnum,
    SocialAdsPlatformsEnum,
    InovationLevelEnum,
    LifeSituationEnum,
    ScalableCapabilityEnum,
    MarketingResponsibilityEnum,
    PostCategoryEnum,
    AgeGroupEnum,
    TypeEnum,
    MarketingExperienceEnum,
    AcquiringCustomersEnum,
    PaymentMethodsEnum,
    PriceLeadershipEnum,
    QualityLeadershipEnum,
    BusinessModelEnum,
    PropertyRightsEnum,
    OfferTypeEnum,
    MarketingChannelsEnum,
    DirectSalesResponsibilityEnum,
    MarketingBudgetEnum,
    PurchaseDecisionEnum,
    PlanRecipientEnum,
    PriceStrategieEnum,
    PriceCalculationEnum,
    DevelopmentStateEnum,
    UspEnum,
    SalesCompensationModelEnum,
    ExistingSalesStructureEnum,
    FoundationTypeEnum,
    LiquiditySectionEnum,
    PricingStrategieEnum,
    CatalogTypeEnum,
    AcquiringCustomerOnlineShopEnum,
}

export default Enums