// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import InformationTargetGroupEnum from "./InformationTargetGroupEnum";
import ExclusiveLeadershipEnum from "./ExclusiveLeadershipEnum";
import TechnologyLeadershipEnum from "./TechnologyLeadershipEnum";
import SpecialistLeadershipEnum from "./SpecialistLeadershipEnum";
import ClientTypeEnum from "./ClientTypeEnum";
import BusinessActivitiesEnum from "./BusinessActivitiesEnum";
import CompanyTargetGroupEnum from "./CompanyTargetGroupEnum";
import TargetMarketEnum from "./TargetMarketEnum";
import ChannelsEnum from "./ChannelsEnum";
import GenerationStatusEnum from "./GenerationStatusEnum";
import PublicTenderEnum from "./PublicTenderEnum";
import BusinessplanTargetEnum from "./BusinessplanTargetEnum";
import CompanyStateEnum from "./CompanyStateEnum";
import StatusEnum from "./StatusEnum";
import CommunityLeadershipEnum from "./CommunityLeadershipEnum";
import CapitalUsageEnum from "./CapitalUsageEnum";
import InovationLevelEnum from "./InovationLevelEnum";
import LifeSituationEnum from "./LifeSituationEnum";
import ScalableCapabilityEnum from "./ScalableCapabilityEnum";
import PostCategoryEnum from "./PostCategoryEnum";
import AgeGroupEnum from "./AgeGroupEnum";
import TypeEnum from "./TypeEnum";
import PriceLeadershipEnum from "./PriceLeadershipEnum";
import QualityLeadershipEnum from "./QualityLeadershipEnum";
import BusinessModelEnum from "./BusinessModelEnum";
import PropertyRightsEnum from "./PropertyRightsEnum";
import OfferTypeEnum from "./OfferTypeEnum";
import PurchaseDecisionEnum from "./PurchaseDecisionEnum";
import PlanRecipientEnum from "./PlanRecipientEnum";
import PriceStrategieEnum from "./PriceStrategieEnum";
import PriceCalculationEnum from "./PriceCalculationEnum";
import DevelopmentStateEnum from "./DevelopmentStateEnum";
import UspEnum from "./UspEnum";
import FoundationTypeEnum from "./FoundationTypeEnum";
import LiquiditySectionEnum from "./LiquiditySectionEnum";
import PricingStrategieEnum from "./PricingStrategieEnum";
import CatalogTypeEnum from "./CatalogTypeEnum";

export const Enums = {
    InformationTargetGroupEnum,
    ExclusiveLeadershipEnum,
    TechnologyLeadershipEnum,
    SpecialistLeadershipEnum,
    ClientTypeEnum,
    BusinessActivitiesEnum,
    CompanyTargetGroupEnum,
    TargetMarketEnum,
    ChannelsEnum,
    GenerationStatusEnum,
    PublicTenderEnum,
    BusinessplanTargetEnum,
    CompanyStateEnum,
    StatusEnum,
    CommunityLeadershipEnum,
    CapitalUsageEnum,
    InovationLevelEnum,
    LifeSituationEnum,
    ScalableCapabilityEnum,
    PostCategoryEnum,
    AgeGroupEnum,
    TypeEnum,
    PriceLeadershipEnum,
    QualityLeadershipEnum,
    BusinessModelEnum,
    PropertyRightsEnum,
    OfferTypeEnum,
    PurchaseDecisionEnum,
    PlanRecipientEnum,
    PriceStrategieEnum,
    PriceCalculationEnum,
    DevelopmentStateEnum,
    UspEnum,
    FoundationTypeEnum,
    LiquiditySectionEnum,
    PricingStrategieEnum,
    CatalogTypeEnum,
}

export default Enums