// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Google = "google"
export const SocialMedia = "social_media"
export const Influencer = "influencer"
export const Vergleichsportale = "vergleichsportale"
export const Empfehlungen = "empfehlungen"
export const Fachmedien = "fachmedien"

/**
 * @see [App\Enums\InformationTargetGroupEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/InformationTargetGroupEnum.php)
 */
export const InformationTargetGroupEnum = { Google, SocialMedia, Influencer, Vergleichsportale, Empfehlungen, Fachmedien } as const

export default InformationTargetGroupEnum