// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Classic = "classic"
export const BetterVersion = "better_version"
export const DisruptivModel = "disruptiv_model"
export const TechInnovation = "tech_innovation"

/**
 * @see [App\Enums\InovationLevelEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/InovationLevelEnum.php)
 */
export const InovationLevelEnum = { Classic, BetterVersion, DisruptivModel, TechInnovation } as const

export default InovationLevelEnum