// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Studierend = "studierend"
export const Berufstaetig = "berufstaetig"
export const Fuehrungskraft = "fuehrungskraft"
export const Familie = "familie"
export const Ruhestand = "ruhestand"

/**
 * @see [App\Enums\LifeSituationEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/LifeSituationEnum.php)
 */
export const LifeSituationEnum = { Studierend, Berufstaetig, Fuehrungskraft, Familie, Ruhestand } as const

export default LifeSituationEnum