// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Income = "income"
export const Investment = "investment"
export const Operational = "operational"
export const Financing = "financing"

/**
 * @see [App\Enums\LiquiditySectionEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/LiquiditySectionEnum.php)
 */
export const LiquiditySectionEnum = { Income, Investment, Operational, Financing } as const

export default LiquiditySectionEnum