// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Ja = "ja"
export const Teilweise = "teilweise"
export const Nein = "nein"

/**
 * @see [App\Enums\MarketingExperienceEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/MarketingExperienceEnum.php)
 */
export const MarketingExperienceEnum = { Ja, Teilweise, Nein } as const

export default MarketingExperienceEnum