// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Website = "website"
export const Crm = "crm"
export const NewsletterSystem = "newsletter_system"
export const TrackingEingerichtet = "tracking_eingerichtet"
export const NichtsVorhanden = "nichts_vorhanden"

/**
 * @see [App\Enums\MarketingInfrastructureEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/MarketingInfrastructureEnum.php)
 */
export const MarketingInfrastructureEnum = { Website, Crm, NewsletterSystem, TrackingEingerichtet, NichtsVorhanden } as const

export default MarketingInfrastructureEnum