// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Seo = "seo"
export const GoogleAds = "google_ads"
export const SocialAds = "social_ads"
export const Influencer = "influencer"
export const Pr = "pr"
export const Events = "events"
export const Kaltakquise = "kaltakquise"
export const Newsletter = "newsletter"
export const ContentMarketing = "content_marketing"

/**
 * @see [App\Enums\MarketingChannelsEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/MarketingChannelsEnum.php)
 */
export const MarketingChannelsEnum = { Seo, GoogleAds, SocialAds, Influencer, Pr, Events, Kaltakquise, Newsletter, ContentMarketing } as const

export default MarketingChannelsEnum