// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const UnterFuenfhundert = "unter_500"
export const FuenfhundertBisZweitausend = "500_bis_2000"
export const ZweitausendBisZehntausend = "2000_bis_10000"
export const UeberZehntausend = "ueber_10000"

/**
 * @see [App\Enums\MarketingBudgetEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/MarketingBudgetEnum.php)
 */
export const MarketingBudgetEnum = { UnterFuenfhundert, FuenfhundertBisZweitausend, ZweitausendBisZehntausend, UeberZehntausend } as const

export default MarketingBudgetEnum