// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Gruender = "gruender"
export const Mitarbeiter = "mitarbeiter"
export const Agentur = "agentur"
export const Freelancer = "freelancer"

/**
 * @see [App\Enums\MarketingResponsibilityEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/MarketingResponsibilityEnum.php)
 */
export const MarketingResponsibilityEnum = { Gruender, Mitarbeiter, Agentur, Freelancer } as const

export default MarketingResponsibilityEnum