// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const PhysischesProdukt = "physisches_produkt"
export const DigitaleSoftware = "digitale_software"
export const MobileApp = "mobile_app"
export const Beratung = "beratung"
export const ServiceVorOrt = "service_vor_ort"
export const OnlineService = "online_service"

/**
 * @see [App\Enums\OfferTypeEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/OfferTypeEnum.php)
 */
export const OfferTypeEnum = { PhysischesProdukt, DigitaleSoftware, MobileApp, Beratung, ServiceVorOrt, OnlineService } as const

export default OfferTypeEnum