// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const PayPal = "paypal"
export const Kreditkarte = "kreditkarte"
export const Sofortueberweisung = "sofortueberweisung"
export const Klarna = "klarna"
export const NochUnklar = "noch_unklar"

/**
 * @see [App\Enums\PaymentMethodsEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PaymentMethodsEnum.php)
 */
export const PaymentMethodsEnum = { PayPal, Kreditkarte, Sofortueberweisung, Klarna, NochUnklar } as const

export default PaymentMethodsEnum