// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Ja = "ja"
export const Nein = "nein"
export const NochUnklar = "noch_unklar"

/**
 * @see [App\Enums\PlanCrmIntroductionEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PlanCrmIntroductionEnum.php)
 */
export const PlanCrmIntroductionEnum = { Ja, Nein, NochUnklar } as const

export default PlanCrmIntroductionEnum