// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const INVESTOR = "investor"
export const EMPLOYMENT_OFFICE = "employment_office"
export const BANK = "bank"
export const GOVERNMENT = "government"
export const OWN = "own"
export const OTHER = "other"

/**
 * @see [App\Enums\PlanRecipientEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PlanRecipientEnum.php)
 */
export const PlanRecipientEnum = { INVESTOR, EMPLOYMENT_OFFICE, BANK, GOVERNMENT, OWN, OTHER } as const

export default PlanRecipientEnum