// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const STARTUPS = "startups"
export const FUNDING = "funding"
export const STRATEGY = "strategy"
export const MARKETING = "marketing"
export const TECHNOLOGY = "technology"
export const LEGAL = "legal"
export const MINDSET = "mindset"
export const NETWORKING = "networking"
export const LEADERSHIP = "leadership"
export const SALES = "sales"
export const GROWTH = "growth"
export const CASE_STUDIES = "case-studies"
export const LESSONS = "lessons"
export const LIFESTYLE = "lifestyle"
export const GUIDES = "guides"

/**
 * @see [App\Enums\PostCategoryEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PostCategoryEnum.php)
 */
export const PostCategoryEnum = { STARTUPS, FUNDING, STRATEGY, MARKETING, TECHNOLOGY, LEGAL, MINDSET, NETWORKING, LEADERSHIP, SALES, GROWTH, CASE_STUDIES, LESSONS, LIFESTYLE, GUIDES } as const

export default PostCategoryEnum