// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const COMPETITOR_PRICE = "competitor_price"
export const COST_WITH_PROFIT = "cost_with_profit"
export const MARKET_PRICE = "market_price"

/**
 * @see [App\Enums\PriceCalculationEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PriceCalculationEnum.php)
 */
export const PriceCalculationEnum = { COMPETITOR_PRICE, COST_WITH_PROFIT, MARKET_PRICE } as const

export default PriceCalculationEnum