// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Premium = "premium"
export const Mittelpreis = "mittelpreis"
export const Discount = "discount"
export const Freemium = "freemium"
export const Nutzungsbasiert = "nutzungsbasiert"
export const Subscription = "subscription"

/**
 * @see [App\Enums\PricingStrategieEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PricingStrategieEnum.php)
 */
export const PricingStrategieEnum = { Premium, Mittelpreis, Discount, Freemium, Nutzungsbasiert, Subscription } as const

export default PricingStrategieEnum