// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const ScaleEffect = "scale_effect"
export const Automation = "automation"
export const DirectSales = "direct_sales"
export const LowFixedCosts = "low_fixed_costs"

/**
 * @see [App\Enums\PriceLeadershipEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PriceLeadershipEnum.php)
 */
export const PriceLeadershipEnum = { ScaleEffect, Automation, DirectSales, LowFixedCosts } as const

export default PriceLeadershipEnum