// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const LOWEST_PRICE = "lowest_price"
export const HIGHEST_PRICE = "highest_price"
export const AVERAGE_PRICE = "average_price"

/**
 * @see [App\Enums\PriceStrategieEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PriceStrategieEnum.php)
 */
export const PriceStrategieEnum = { LOWEST_PRICE, HIGHEST_PRICE, AVERAGE_PRICE } as const

export default PriceStrategieEnum