// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Patent = "patent"
export const Marke = "marke"
export const Designschutz = "designschutz"
export const Keine = "keine"

/**
 * @see [App\Enums\PropertyRightsEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PropertyRightsEnum.php)
 */
export const PropertyRightsEnum = { Patent, Marke, Designschutz, Keine } as const

export default PropertyRightsEnum