// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const JaRegelmaessig = "ja_regelmaessig"
export const Teilweise = "teilweise"
export const Nein = "nein"

/**
 * @see [App\Enums\PublicTenderEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PublicTenderEnum.php)
 */
export const PublicTenderEnum = { JaRegelmaessig, Teilweise, Nein } as const

export default PublicTenderEnum