// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Preis = "preis"
export const Qualitaet = "qualitaet"
export const Marke = "marke"
export const Empfehlung = "empfehlung"
export const Emotion = "emotion"
export const Bequemlichkeit = "bequemlichkeit"
export const Sicherheit = "sicherheit"
export const Nachhaltigkeit = "nachhaltigkeit"

/**
 * @see [App\Enums\PurchaseDecisionEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/PurchaseDecisionEnum.php)
 */
export const PurchaseDecisionEnum = { Preis, Qualitaet, Marke, Empfehlung, Emotion, Bequemlichkeit, Sicherheit, Nachhaltigkeit } as const

export default PurchaseDecisionEnum