// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Certification = "certification"
export const Reference = "reference"
export const TestSeal = "test_seal"
export const ExpertStatus = "expert_status"

/**
 * @see [App\Enums\QualityLeadershipEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/QualityLeadershipEnum.php)
 */
export const QualityLeadershipEnum = { Certification, Reference, TestSeal, ExpertStatus } as const

export default QualityLeadershipEnum