// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Fixgehalt = "fixgehalt"
export const Provision = "provision"
export const Kombination = "kombination"

/**
 * @see [App\Enums\SalesCompensationModelEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/SalesCompensationModelEnum.php)
 */
export const SalesCompensationModelEnum = { Fixgehalt, Provision, Kombination } as const

export default SalesCompensationModelEnum