// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Local = "local"
export const National = "national"
export const International = "international"
export const Digital = "digital"

/**
 * @see [App\Enums\ScalableCapabilityEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/ScalableCapabilityEnum.php)
 */
export const ScalableCapabilityEnum = { Local, National, International, Digital } as const

export default ScalableCapabilityEnum