// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const EigenerVersand = "eigener_versand"
export const FulfillmentDienstleister = "fulfillment_dienstleister"
export const NochOffen = "noch_offen"

/**
 * @see [App\Enums\ShippingOrganizationEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/ShippingOrganizationEnum.php)
 */
export const ShippingOrganizationEnum = { EigenerVersand, FulfillmentDienstleister, NochOffen } as const

export default ShippingOrganizationEnum