// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Meta = "meta"
export const TikTok = "tiktok"
export const LinkedIn = "linkedin"
export const Pinterest = "pinterest"
export const X = "x"

/**
 * @see [App\Enums\SocialAdsPlatformsEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/SocialAdsPlatformsEnum.php)
 */
export const SocialAdsPlatformsEnum = { Meta, TikTok, LinkedIn, Pinterest, X } as const

export default SocialAdsPlatformsEnum