// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Niche = "niche"
export const Branch = "branch"
export const Region = "region"
export const CustomerSegment = "customer_segment"

/**
 * @see [App\Enums\SpecialistLeadershipEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/SpecialistLeadershipEnum.php)
 */
export const SpecialistLeadershipEnum = { Niche, Branch, Region, CustomerSegment } as const

export default SpecialistLeadershipEnum