// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const DRAFT = "draft"
export const IN_PROGRESS = "in_progress"
export const COMPLETED = "completed"

/**
 * @see [App\Enums\StatusEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/StatusEnum.php)
 */
export const StatusEnum = { DRAFT, IN_PROGRESS, COMPLETED } as const

export default StatusEnum