// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const Wachsend = "wachsend"
export const Reif = "reif"
export const Schrumpfend = "schrumpfend"
export const Neu = "neu"

/**
 * @see [App\Enums\TargetMarketEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/TargetMarketEnum.php)
 */
export const TargetMarketEnum = { Wachsend, Reif, Schrumpfend, Neu } as const

export default TargetMarketEnum