// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const SelfDevelopment = "self_development"
export const Patent = "patent"
export const ProprietaryData = "proprietary_data"
export const AiModels = "ai_models"

/**
 * @see [App\Enums\TechnologyLeadershipEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/TechnologyLeadershipEnum.php)
 */
export const TechnologyLeadershipEnum = { SelfDevelopment, Patent, ProprietaryData, AiModels } as const

export default TechnologyLeadershipEnum