// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const INCOME = "income"
export const EXPENSE = "expense"

/**
 * @see [App\Enums\TypeEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/TypeEnum.php)
 */
export const TypeEnum = { INCOME, EXPENSE } as const

export default TypeEnum