// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const PriceLeadership = "price_leadership"
export const QualityLeadership = "quality_leadership"
export const SpecialistLeadership = "specialist_leadership"
export const TechnologyLeadership = "technology_leadership"
export const ExclusiveLeadership = "exclusive_leadership"
export const CommunityLeadership = "community_leadership"

/**
 * @see [App\Enums\UspEnum](/Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Enums/UspEnum.php)
 */
export const UspEnum = { PriceLeadership, QualityLeadership, SpecialistLeadership, TechnologyLeadership, ExclusiveLeadership, CommunityLeadership } as const

export default UspEnum