// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/boost/src/BoostServiceProvider.php:114
 * @route "/_boost/browser-logs"
 */
export const browserLogs = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: browserLogs.url(options),
    method: "post",
})

browserLogs.definition = {
    methods: ["post"],
    url: "/_boost/browser-logs",
} satisfies RouteDefinition<["post"]>

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/boost/src/BoostServiceProvider.php:114
 * @route "/_boost/browser-logs"
 */
browserLogs.url = (options?: RouteQueryOptions) => {
    return browserLogs.definition.url + queryParams(options)
}

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/boost/src/BoostServiceProvider.php:114
 * @route "/_boost/browser-logs"
 */
browserLogs.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: browserLogs.url(options),
    method: "post",
})

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/boost/src/BoostServiceProvider.php:114
 * @route "/_boost/browser-logs"
 */
const browserLogsForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: browserLogs.url(options),
    method: "post",
})

/**
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/boost/src/BoostServiceProvider.php:114
 * @route "/_boost/browser-logs"
 */
browserLogsForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: browserLogs.url(options),
    method: "post",
})

browserLogs.form = browserLogsForm

const boost = {
    "browser-logs": browserLogs,
}

export default boost