// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Enums from "./Enums";
import Http from "./Http";

export const App = {
    Enums,
    Http,
}

export default App