// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:211
 * @route "/businessplans/{businessPlan}/transactions"
 */
export const store = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/businessplans/{businessPlan}/transactions",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:211
 * @route "/businessplans/{businessPlan}/transactions"
 */
store.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return store.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:211
 * @route "/businessplans/{businessPlan}/transactions"
 */
store.post = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:211
 * @route "/businessplans/{businessPlan}/transactions"
 */
const storeForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:211
 * @route "/businessplans/{businessPlan}/transactions"
 */
storeForm.post = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})

store.form = storeForm

const transaction = {
    store,
}

export default transaction