// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Controllers from "./Controllers";

export const Http = {
    Controllers,
}

export default Http