// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import Http from "./Http";

export const Telescope = {
    Http,
}

export default Telescope