// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { App } from "./types";

declare module '@inertiajs/core' {
    export interface InertiaConfig {
     sharedPageProps: { name: unknown, auth: {user: App.Models.User | null }, sidebarOpen: boolean } 
    }
}