// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\BusinessPlanController::saveStep
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:115
 * @route "/businessplans/{businessPlan}/save-step"
 */
export const saveStep = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: saveStep.url(args, options),
    method: "put",
})

saveStep.definition = {
    methods: ["put"],
    url: "/businessplans/{businessPlan}/save-step",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::saveStep
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:115
 * @route "/businessplans/{businessPlan}/save-step"
 */
saveStep.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return saveStep.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::saveStep
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:115
 * @route "/businessplans/{businessPlan}/save-step"
 */
saveStep.put = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: saveStep.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::saveStep
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:115
 * @route "/businessplans/{businessPlan}/save-step"
 */
const saveStepForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: saveStep.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::saveStep
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:115
 * @route "/businessplans/{businessPlan}/save-step"
 */
saveStepForm.put = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: saveStep.url(args, formSafeOptions("put", options)),
    method: "post",
})

saveStep.form = saveStepForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:207
 * @route "/businessplans/{businessPlan}/transactions"
 */
export const storeTransaction = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: storeTransaction.url(args, options),
    method: "post",
})

storeTransaction.definition = {
    methods: ["post"],
    url: "/businessplans/{businessPlan}/transactions",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:207
 * @route "/businessplans/{businessPlan}/transactions"
 */
storeTransaction.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return storeTransaction.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:207
 * @route "/businessplans/{businessPlan}/transactions"
 */
storeTransaction.post = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: storeTransaction.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:207
 * @route "/businessplans/{businessPlan}/transactions"
 */
const storeTransactionForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: storeTransaction.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::storeTransaction
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:207
 * @route "/businessplans/{businessPlan}/transactions"
 */
storeTransactionForm.post = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: storeTransaction.url(args, options),
    method: "post",
})

storeTransaction.form = storeTransactionForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/businessplans",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:73
 * @route "/businessplans"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})

index.form = indexForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
export const create = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: create.url(options),
    method: "get",
})

create.definition = {
    methods: ["get","head"],
    url: "/businessplans/create",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
create.url = (options?: RouteQueryOptions) => {
    return create.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
create.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
create.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: create.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
const createForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
createForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: create.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::create
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:85
 * @route "/businessplans/create"
 */
createForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: create.url(formSafeOptions("head", options)),
    method: "get",
})

create.form = createForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:99
 * @route "/businessplans"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/businessplans",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:99
 * @route "/businessplans"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:99
 * @route "/businessplans"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:99
 * @route "/businessplans"
 */
const storeForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:99
 * @route "/businessplans"
 */
storeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

store.form = storeForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
export const show = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/businessplans/{businessPlan}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
show.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return show.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
show.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
show.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
const showForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
showForm.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:133
 * @route "/businessplans/{businessPlan}"
 */
showForm.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, formSafeOptions("head", options)),
    method: "get",
})

show.form = showForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
export const edit = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

edit.definition = {
    methods: ["get","head"],
    url: "/businessplans/{businessPlan}/edit",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
edit.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return edit.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
edit.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
edit.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: edit.url(args, options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
const editForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
editForm.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::edit
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:169
 * @route "/businessplans/{businessPlan}/edit"
 */
editForm.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: edit.url(args, formSafeOptions("head", options)),
    method: "get",
})

edit.form = editForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
export const update = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put","patch"],
    url: "/businessplans/{businessPlan}",
} satisfies RouteDefinition<["put","patch"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
update.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return update.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
update.put = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
update.patch = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"patch"> => ({
    url: update.url(args, options),
    method: "patch",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
const updateForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
updateForm.put = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:188
 * @route "/businessplans/{businessPlan}"
 */
updateForm.patch = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("patch", options)),
    method: "post",
})

update.form = updateForm
/**
 * @see \App\Http\Controllers\BusinessPlanController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:215
 * @route "/businessplans/{businessPlan}"
 */
export const destroy = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/businessplans/{businessPlan}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\BusinessPlanController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:215
 * @route "/businessplans/{businessPlan}"
 */
destroy.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return destroy.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:215
 * @route "/businessplans/{businessPlan}"
 */
destroy.delete = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:215
 * @route "/businessplans/{businessPlan}"
 */
const destroyForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: destroy.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanController.php:215
 * @route "/businessplans/{businessPlan}"
 */
destroyForm.delete = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: destroy.url(args, formSafeOptions("delete", options)),
    method: "post",
})

destroy.form = destroyForm

const BusinessPlanController = {
    saveStep,
    storeTransaction,
    index,
    create,
    store,
    show,
    edit,
    update,
    destroy,
}

export default BusinessPlanController