// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
export const index = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(args, options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/businessplans/{businessPlan}/checks",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
index.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return index.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
index.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
index.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(args, options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
const indexForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
indexForm.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:44
 * @route "/businessplans/{businessPlan}/checks"
 */
indexForm.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(args, formSafeOptions("head", options)),
    method: "get",
})

index.form = indexForm
/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
export const stream = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: stream.url(args, options),
    method: "get",
})

stream.definition = {
    methods: ["get","head"],
    url: "/businessplans/{businessPlan}/checks/{group}/stream",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
stream.url = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
        group: args[1],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
        group: args.group,
    }
    
    return stream.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace("{group}", parsedArgs.group.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
stream.get = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: stream.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
stream.head = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: stream.url(args, options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
const streamForm = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: stream.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
streamForm.get = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: stream.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanCheckController::stream
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanCheckController.php:59
 * @route "/businessplans/{businessPlan}/checks/{group}/stream"
 */
streamForm.head = (args: { businessPlan: number | { id: number }, group: string | number } | [ businessPlan: number | { id: number }, group: string | number ], options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: stream.url(args, formSafeOptions("head", options)),
    method: "get",
})

stream.form = streamForm

const BusinessPlanCheckController = {
    index,
    stream,
}

export default BusinessPlanCheckController