// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:12
 * @route "/businessplans/{businessPlan}/sections"
 */
export const store = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/businessplans/{businessPlan}/sections",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:12
 * @route "/businessplans/{businessPlan}/sections"
 */
store.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return store.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:12
 * @route "/businessplans/{businessPlan}/sections"
 */
store.post = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:12
 * @route "/businessplans/{businessPlan}/sections"
 */
const storeForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:12
 * @route "/businessplans/{businessPlan}/sections"
 */
storeForm.post = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(args, options),
    method: "post",
})

store.form = storeForm
/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:35
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
export const update = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

update.definition = {
    methods: ["put"],
    url: "/businessplans/{businessPlan}/sections/{section}",
} satisfies RouteDefinition<["put"]>

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:35
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
update.url = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
        section: args[1],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
        section: typeof args.section === "object" ? args.section.id : args.section,
    }
    
    return update.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace("{section}", parsedArgs.section.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:35
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
update.put = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"put"> => ({
    url: update.url(args, options),
    method: "put",
})

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:35
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
const updateForm = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("put", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::update
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:35
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
updateForm.put = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: update.url(args, formSafeOptions("put", options)),
    method: "post",
})

update.form = updateForm
/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:49
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
export const destroy = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

destroy.definition = {
    methods: ["delete"],
    url: "/businessplans/{businessPlan}/sections/{section}",
} satisfies RouteDefinition<["delete"]>

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:49
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
destroy.url = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions) => {
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
        section: args[1],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
        section: typeof args.section === "object" ? args.section.id : args.section,
    }
    
    return destroy.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace("{section}", parsedArgs.section.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:49
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
destroy.delete = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteDefinition<"delete"> => ({
    url: destroy.url(args, options),
    method: "delete",
})

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:49
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
const destroyForm = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: destroy.url(args, formSafeOptions("delete", options)),
    method: "post",
})

/**
 * @see \App\Http\Controllers\BusinessPlanSectionController::destroy
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanSectionController.php:49
 * @route "/businessplans/{businessPlan}/sections/{section}"
 */
destroyForm.delete = (args: { businessPlan: number | { id: number }, section: number | { id: number } } | [ businessPlan: number | { id: number }, section: number | { id: number } ], options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: destroy.url(args, formSafeOptions("delete", options)),
    method: "post",
})

destroy.form = destroyForm

const BusinessPlanSectionController = {
    store,
    update,
    destroy,
}

export default BusinessPlanSectionController