// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/dashboard",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\DashboardController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/DashboardController.php:22
 * @route "/dashboard"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})

index.form = indexForm

const DashboardController = {
    index,
}

export default DashboardController