// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import BusinessPlanCheckController from "./BusinessPlanCheckController";
import BusinessPlanPdfController from "./BusinessPlanPdfController";
import BusinessPlanController from "./BusinessPlanController";
import SubscriptionController from "./SubscriptionController";
import PostController from "./PostController";
import BusinessPlanSectionController from "./BusinessPlanSectionController";
import DashboardController from "./DashboardController";
import Settings from "./Settings";

export const Controllers = {
    BusinessPlanCheckController,
    BusinessPlanPdfController,
    BusinessPlanController,
    SubscriptionController,
    PostController,
    BusinessPlanSectionController,
    DashboardController,
    Settings,
}

export default Controllers