// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

index.definition = {
    methods: ["get","head"],
    url: "/user/two-factor-recovery-codes",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
index.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: index.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
index.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: index.url(options),
    method: "head",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
indexForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:19
 * @route "/user/two-factor-recovery-codes"
 */
indexForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: index.url(formSafeOptions("head", options)),
    method: "get",
})

index.form = indexForm
/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:38
 * @route "/user/two-factor-recovery-codes"
 */
export const store = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

store.definition = {
    methods: ["post"],
    url: "/user/two-factor-recovery-codes",
} satisfies RouteDefinition<["post"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:38
 * @route "/user/two-factor-recovery-codes"
 */
store.url = (options?: RouteQueryOptions) => {
    return store.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:38
 * @route "/user/two-factor-recovery-codes"
 */
store.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: store.url(options),
    method: "post",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:38
 * @route "/user/two-factor-recovery-codes"
 */
const storeForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\RecoveryCodeController::store
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/RecoveryCodeController.php:38
 * @route "/user/two-factor-recovery-codes"
 */
storeForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: store.url(options),
    method: "post",
})

store.form = storeForm

const RecoveryCodeController = {
    index,
    store,
}

export default RecoveryCodeController