// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
export const show = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/user/two-factor-qr-code",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
show.url = (options?: RouteQueryOptions) => {
    return show.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
show.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
show.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(options),
    method: "head",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
const showForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
showForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(options),
    method: "get",
})

/**
 * @see \Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/fortify/src/Http/Controllers/TwoFactorQrCodeController.php:16
 * @route "/user/two-factor-qr-code"
 */
showForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(formSafeOptions("head", options)),
    method: "get",
})

show.form = showForm

const TwoFactorQrCodeController = {
    show,
}

export default TwoFactorQrCodeController