// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";
import pdf81d01da from "./pdf";

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
export const pdf = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: pdf.url(args, options),
    method: "get",
})

pdf.definition = {
    methods: ["get","head"],
    url: "/business-plan/{businessPlan}/pdf",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
pdf.url = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { businessPlan: args }
    }
    
    if (typeof args === "object" && !Array.isArray(args) && "id" in args) {
        args = { businessPlan: args.id }
    }
    
    if (Array.isArray(args)) {
        args = {
        businessPlan: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        businessPlan: typeof args.businessPlan === "object" ? args.businessPlan.id : args.businessPlan,
    }
    
    return pdf.definition.url
        .replace("{businessPlan}", parsedArgs.businessPlan.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
pdf.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: pdf.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
pdf.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: pdf.url(args, options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
const pdfForm = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: pdf.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
pdfForm.get = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: pdf.url(args, options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\BusinessPlanPdfController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/BusinessPlanPdfController.php:16
 * @route "/business-plan/{businessPlan}/pdf"
 */
pdfForm.head = (args: { businessPlan: number | { id: number } } | [ businessPlan: number | { id: number } ] | number | { id: number }, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: pdf.url(args, formSafeOptions("head", options)),
    method: "get",
})

pdf.form = pdfForm

const businessPlan = {
    pdf: Object.assign(pdf, pdf81d01da),
}

export default businessPlan