// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \Laravel\Telescope\Http\Controllers\DumpController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/DumpController.php:42
 * @route "/telescope/telescope-api/dumps"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: index.url(options),
    method: "post",
})

index.definition = {
    methods: ["post"],
    url: "/telescope/telescope-api/dumps",
} satisfies RouteDefinition<["post"]>

/**
 * @see \Laravel\Telescope\Http\Controllers\DumpController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/DumpController.php:42
 * @route "/telescope/telescope-api/dumps"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Telescope\Http\Controllers\DumpController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/DumpController.php:42
 * @route "/telescope/telescope-api/dumps"
 */
index.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: index.url(options),
    method: "post",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\DumpController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/DumpController.php:42
 * @route "/telescope/telescope-api/dumps"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: index.url(options),
    method: "post",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\DumpController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/DumpController.php:42
 * @route "/telescope/telescope-api/dumps"
 */
indexForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: index.url(options),
    method: "post",
})

index.form = indexForm

const DumpController = {
    index,
}

export default DumpController