// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import QueriesController from "./QueriesController";
import LogController from "./LogController";
import HomeController from "./HomeController";
import QueueBatchesController from "./QueueBatchesController";
import DumpController from "./DumpController";
import NotificationsController from "./NotificationsController";
import MailController from "./MailController";
import RedisController from "./RedisController";
import EntriesController from "./EntriesController";
import CommandsController from "./CommandsController";
import MonitoredTagController from "./MonitoredTagController";
import ViewsController from "./ViewsController";
import ModelsController from "./ModelsController";
import MailEmlController from "./MailEmlController";
import ScheduleController from "./ScheduleController";
import EventsController from "./EventsController";
import GatesController from "./GatesController";
import QueueController from "./QueueController";
import RecordingController from "./RecordingController";
import ExceptionController from "./ExceptionController";
import MailHtmlController from "./MailHtmlController";
import RequestsController from "./RequestsController";
import CacheController from "./CacheController";
import ClientRequestController from "./ClientRequestController";

export const Controllers = {
    QueriesController,
    LogController,
    HomeController,
    QueueBatchesController,
    DumpController,
    NotificationsController,
    MailController,
    RedisController,
    EntriesController,
    CommandsController,
    MonitoredTagController,
    ViewsController,
    ModelsController,
    MailEmlController,
    ScheduleController,
    EventsController,
    GatesController,
    QueueController,
    RecordingController,
    ExceptionController,
    MailHtmlController,
    RequestsController,
    CacheController,
    ClientRequestController,
}

export default Controllers