// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
export const show = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/telescope/telescope-api/mail/{telescopeEntryId}/preview",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
show.url = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { telescopeEntryId: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        telescopeEntryId: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        telescopeEntryId: args.telescopeEntryId,
    }
    
    return show.definition.url
        .replace("{telescopeEntryId}", parsedArgs.telescopeEntryId.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
show.get = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
show.head = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
const showForm = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
showForm.get = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\MailHtmlController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/MailHtmlController.php:17
 * @route "/telescope/telescope-api/mail/{telescopeEntryId}/preview"
 */
showForm.head = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, formSafeOptions("head", options)),
    method: "get",
})

show.form = showForm

const MailHtmlController = {
    show,
}

export default MailHtmlController