// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { applyUrlDefaults, formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../../index";

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:33
 * @route "/telescope/telescope-api/queries"
 */
export const index = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: index.url(options),
    method: "post",
})

index.definition = {
    methods: ["post"],
    url: "/telescope/telescope-api/queries",
} satisfies RouteDefinition<["post"]>

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:33
 * @route "/telescope/telescope-api/queries"
 */
index.url = (options?: RouteQueryOptions) => {
    return index.definition.url + queryParams(options)
}

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:33
 * @route "/telescope/telescope-api/queries"
 */
index.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: index.url(options),
    method: "post",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:33
 * @route "/telescope/telescope-api/queries"
 */
const indexForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: index.url(options),
    method: "post",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::index
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:33
 * @route "/telescope/telescope-api/queries"
 */
indexForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: index.url(options),
    method: "post",
})

index.form = indexForm
/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
export const show = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

show.definition = {
    methods: ["get","head"],
    url: "/telescope/telescope-api/queries/{telescopeEntryId}",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
show.url = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions) => {
    if (typeof args === "string" || typeof args === "number") {
        args = { telescopeEntryId: args }
    }
    
    if (Array.isArray(args)) {
        args = {
        telescopeEntryId: args[0],
    }
    }
    
    args = applyUrlDefaults(args)
    
    const parsedArgs = {
        telescopeEntryId: args.telescopeEntryId,
    }
    
    return show.definition.url
        .replace("{telescopeEntryId}", parsedArgs.telescopeEntryId.toString())
        .replace(/\/+$/, "") + queryParams(options)
}

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
show.get = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: show.url(args, options),
    method: "get",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
show.head = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: show.url(args, options),
    method: "head",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
const showForm = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
showForm.get = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, options),
    method: "get",
})

/**
 * @see \Laravel\Telescope\Http\Controllers\QueriesController::show
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/vendor/laravel/telescope/src/Http/Controllers/QueriesController.php:51
 * @route "/telescope/telescope-api/queries/{telescopeEntryId}"
 */
showForm.head = (args: { telescopeEntryId: string | number } | [ telescopeEntryId: string | number ] | string | number, options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: show.url(args, formSafeOptions("head", options)),
    method: "get",
})

show.form = showForm

const QueriesController = {
    index,
    show,
}

export default QueriesController