// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../index";

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
export const checkout = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: checkout.url(options),
    method: "get",
})

checkout.definition = {
    methods: ["get","head"],
    url: "/subscription/checkout",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
checkout.url = (options?: RouteQueryOptions) => {
    return checkout.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
checkout.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: checkout.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
checkout.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: checkout.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
const checkoutForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: checkout.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
checkoutForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: checkout.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::checkout
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:9
 * @route "/subscription/checkout"
 */
checkoutForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: checkout.url(formSafeOptions("head", options)),
    method: "get",
})

checkout.form = checkoutForm
/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
export const portal = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: portal.url(options),
    method: "get",
})

portal.definition = {
    methods: ["get","head"],
    url: "/subscription/portal",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
portal.url = (options?: RouteQueryOptions) => {
    return portal.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
portal.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: portal.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
portal.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: portal.url(options),
    method: "head",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
const portalForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: portal.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
portalForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: portal.url(options),
    method: "get",
})

/**
 * @see \App\Http\Controllers\SubscriptionController::portal
 * @see /Applications/XAMPP/xamppfiles/htdocs/Stratify/app/Http/Controllers/SubscriptionController.php:26
 * @route "/subscription/portal"
 */
portalForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: portal.url(formSafeOptions("head", options)),
    method: "get",
})

portal.form = portalForm

const subscription = {
    checkout,
    portal,
}

export default subscription