// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import RedirectController from "./RedirectController";

export const Routing = {
    RedirectController,
}

export default Routing